### ISSUE TITLE
Крос проверка дз2

### ISSUE THREAD

**Issue by AJShum** [aa1dar/MyTodoApp#3]
Локальная база данных не создается автоматический. При создании базы в ручную не создаются таблицы и не сохраняются записи. p.s. может быть это только у меня так.

**Comment by AJShum** [comment]
Итого:
Организовано сохранение данных на диск при помощи одной из представленных библиотек (-1,5 балла).

**Comment by aa1dar** [comment]
Спасибо за ревью. Можно уточнить как база данных может создаваться не автоматически(вручную)? И ты запускал релиз сборку которая в Github Releases или у себя в Debug?

**Comment by AJShum** [comment]
При запуске приложения по указанному пути файл с названием базы данных не появляется, я попробовал его создать и все равно не работает. Я проверял у себя в Debug.

**Comment by aa1dar** [comment]
А по какому пути ты его искал, если не секрет?

**Comment by AJShum** [comment]
flutter: Directory: '/home/alexander/Documents'

**Comment by aa1dar** [comment]
Понятно. он там не должен создаваться. А релизную сборку ты пробовал запускать? У тебя там тоже ничего не работает? Можешь пожалуйста сказать версию Android эмулятора/телефона?

**Comment by AJShum** [comment]
Я на Linux проверял, сейчас проверю релизную версию на телефоне.

**Comment by aa1dar** [comment]
sqflite не работает в чистом виде на Linux, поэтому и ничего не работает
https://pub.dev/packages/sqflite

**Comment by AJShum** [comment]
Установил релизную версию. Добавил задачу. Выключил интернет. Перезапустил приложение. Список задач пустой.

**Comment by AJShum** [comment]
Не та версия, извини. Поставил правильную. При запуске без интернета CircularProgressIndicator крутится.

**Comment by aa1dar** [comment]
В критериях к 2 дз не было сказано, что нужно обрабатывать поведение работы приложения без интернета)
